
#!/bin/bash

#path to directories
GTEST_DIR="/home/szymon/TDD/googletest"
GMOCK_DIR="/home/szymon/TDD/googlemock"


#run compiler
g++ -std=c++11 -isystem ${GTEST_DIR}/include -isystem ${GMOCK_DIR}/include -pthread mainTest.cpp hitPointTest.cpp lib/libgmock.a -o testUnit -lm

#g++ -std=c++11 -pthread main.cpp -o ellip 
